- name: DeployHeroku
        uses: akhileshns/heroku-deploy@v3.12.12 
        with:
          heroku_api_key: ${{ secrets.heroku_api_key }}
          heroku_app_name: favouritemovie111
          heroku_email: ${{ secrets.heroku_email }}
          branch: ${{ github.ref_name }}
        env:
          HD_SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
          HD_SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
          HD_SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}